package models;
// Generated 30-may-2018 16:39:10 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name="Empresas")
public class Empresas implements java.io.Serializable {
	
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	private Integer idEmpresa;
	@Column
	private String nombre;
	@Column
	private String cif;


	public Empresas() {
	}

	public Empresas(String nombre, String cif) {
		this.nombre = nombre;
		this.cif = cif;
	}

	public Empresas(String nombre, String cif, Set trabajadorbbdds) {
		this.nombre = nombre;
		this.cif = cif;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}


}
