package models;
// Generated 30-may-2018 16:39:10 by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nomina generated by hbm2java
 */

@Entity
@Table(name="Nomina")
public class Nomina implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	private Integer idNomina;
	@Column
	private Trabajadorbbdd trabajadorbbdd;
	@Column
	private int mes;
	@Column
	private int anio;
	@Column
	private int numeroTrienios;
	@Column
	private double importeTrienios;
	@Column
	private double importeSalarioMes;
	@Column
	private double importeComplementoMes;
	@Column
	private double valorProrrateo;
	@Column
	private double brutoAnual;
	@Column
	private double irpf;
	@Column
	private double importeIrpf;
	@Column
	private double baseEmpresario;
	@Column
	private double seguridadSocialEmpresario;
	@Column
	private double importeSeguridadSocialEmpresario;
	@Column
	private double desempleoEmpresario;
	@Column
	private double importeDesempleoEmpresario;
	@Column
	private double formacionEmpresario;
	@Column
	private double importeFormacionEmpresario;
	@Column
	private double accidentesTrabajoEmpresario;
	@Column
	private double importeAccidentesTrabajoEmpresario;
	@Column
	private double fogasaempresario;
	@Column
	private double importeFogasaempresario;
	@Column
	private double seguridadSocialTrabajador;
	@Column
	private double importeSeguridadSocialTrabajador;
	@Column
	private double desempleoTrabajador;
	@Column
	private double importeDesempleoTrabajador;
	@Column
	private double formacionTrabajador;
	@Column
	private double importeFormacionTrabajador;
	@Column
	private double brutoNomina;
	@Column
	private double liquidoNomina;
	@Column
	private double costeTotalEmpresario;
	

	public Nomina() {
	}

	public Nomina(Trabajadorbbdd trabajadorbbdd, int mes, int anio, int numeroTrienios, double importeTrienios,
			double importeSalarioMes, double importeComplementoMes, double valorProrrateo, double brutoAnual,
			double irpf, double importeIrpf, double baseEmpresario, double seguridadSocialEmpresario,
			double importeSeguridadSocialEmpresario, double desempleoEmpresario, double importeDesempleoEmpresario,
			double formacionEmpresario, double importeFormacionEmpresario, double accidentesTrabajoEmpresario,
			double importeAccidentesTrabajoEmpresario, double fogasaempresario, double importeFogasaempresario,
			double seguridadSocialTrabajador, double importeSeguridadSocialTrabajador, double desempleoTrabajador,
			double importeDesempleoTrabajador, double formacionTrabajador, double importeFormacionTrabajador,
			double brutoNomina, double liquidoNomina, double costeTotalEmpresario) {
		this.trabajadorbbdd = trabajadorbbdd;
		this.mes = mes;
		this.anio = anio;
		this.numeroTrienios = numeroTrienios;
		this.importeTrienios = importeTrienios;
		this.importeSalarioMes = importeSalarioMes;
		this.importeComplementoMes = importeComplementoMes;
		this.valorProrrateo = valorProrrateo;
		this.brutoAnual = brutoAnual;
		this.irpf = irpf;
		this.importeIrpf = importeIrpf;
		this.baseEmpresario = baseEmpresario;
		this.seguridadSocialEmpresario = seguridadSocialEmpresario;
		this.importeSeguridadSocialEmpresario = importeSeguridadSocialEmpresario;
		this.desempleoEmpresario = desempleoEmpresario;
		this.importeDesempleoEmpresario = importeDesempleoEmpresario;
		this.formacionEmpresario = formacionEmpresario;
		this.importeFormacionEmpresario = importeFormacionEmpresario;
		this.accidentesTrabajoEmpresario = accidentesTrabajoEmpresario;
		this.importeAccidentesTrabajoEmpresario = importeAccidentesTrabajoEmpresario;
		this.fogasaempresario = fogasaempresario;
		this.importeFogasaempresario = importeFogasaempresario;
		this.seguridadSocialTrabajador = seguridadSocialTrabajador;
		this.importeSeguridadSocialTrabajador = importeSeguridadSocialTrabajador;
		this.desempleoTrabajador = desempleoTrabajador;
		this.importeDesempleoTrabajador = importeDesempleoTrabajador;
		this.formacionTrabajador = formacionTrabajador;
		this.importeFormacionTrabajador = importeFormacionTrabajador;
		this.brutoNomina = brutoNomina;
		this.liquidoNomina = liquidoNomina;
		this.costeTotalEmpresario = costeTotalEmpresario;
	}

	public Integer getIdNomina() {
		return this.idNomina;
	}

	public void setIdNomina(Integer idNomina) {
		this.idNomina = idNomina;
	}

	public Trabajadorbbdd getTrabajadorbbdd() {
		return this.trabajadorbbdd;
	}

	public void setTrabajadorbbdd(Trabajadorbbdd trabajadorbbdd) {
		this.trabajadorbbdd = trabajadorbbdd;
	}

	public int getMes() {
		return this.mes;
	}

	public void setMes(int mes) {
		this.mes = mes;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public int getNumeroTrienios() {
		return this.numeroTrienios;
	}

	public void setNumeroTrienios(int numeroTrienios) {
		this.numeroTrienios = numeroTrienios;
	}

	public double getImporteTrienios() {
		return this.importeTrienios;
	}

	public void setImporteTrienios(double importeTrienios) {
		this.importeTrienios = importeTrienios;
	}

	public double getImporteSalarioMes() {
		return this.importeSalarioMes;
	}

	public void setImporteSalarioMes(double importeSalarioMes) {
		this.importeSalarioMes = importeSalarioMes;
	}

	public double getImporteComplementoMes() {
		return this.importeComplementoMes;
	}

	public void setImporteComplementoMes(double importeComplementoMes) {
		this.importeComplementoMes = importeComplementoMes;
	}

	public double getValorProrrateo() {
		return this.valorProrrateo;
	}

	public void setValorProrrateo(double valorProrrateo) {
		this.valorProrrateo = valorProrrateo;
	}

	public double getBrutoAnual() {
		return this.brutoAnual;
	}

	public void setBrutoAnual(double brutoAnual) {
		this.brutoAnual = brutoAnual;
	}

	public double getIrpf() {
		return this.irpf;
	}

	public void setIrpf(double irpf) {
		this.irpf = irpf;
	}

	public double getImporteIrpf() {
		return this.importeIrpf;
	}

	public void setImporteIrpf(double importeIrpf) {
		this.importeIrpf = importeIrpf;
	}

	public double getBaseEmpresario() {
		return this.baseEmpresario;
	}

	public void setBaseEmpresario(double baseEmpresario) {
		this.baseEmpresario = baseEmpresario;
	}

	public double getSeguridadSocialEmpresario() {
		return this.seguridadSocialEmpresario;
	}

	public void setSeguridadSocialEmpresario(double seguridadSocialEmpresario) {
		this.seguridadSocialEmpresario = seguridadSocialEmpresario;
	}

	public double getImporteSeguridadSocialEmpresario() {
		return this.importeSeguridadSocialEmpresario;
	}

	public void setImporteSeguridadSocialEmpresario(double importeSeguridadSocialEmpresario) {
		this.importeSeguridadSocialEmpresario = importeSeguridadSocialEmpresario;
	}

	public double getDesempleoEmpresario() {
		return this.desempleoEmpresario;
	}

	public void setDesempleoEmpresario(double desempleoEmpresario) {
		this.desempleoEmpresario = desempleoEmpresario;
	}

	public double getImporteDesempleoEmpresario() {
		return this.importeDesempleoEmpresario;
	}

	public void setImporteDesempleoEmpresario(double importeDesempleoEmpresario) {
		this.importeDesempleoEmpresario = importeDesempleoEmpresario;
	}

	public double getFormacionEmpresario() {
		return this.formacionEmpresario;
	}

	public void setFormacionEmpresario(double formacionEmpresario) {
		this.formacionEmpresario = formacionEmpresario;
	}

	public double getImporteFormacionEmpresario() {
		return this.importeFormacionEmpresario;
	}

	public void setImporteFormacionEmpresario(double importeFormacionEmpresario) {
		this.importeFormacionEmpresario = importeFormacionEmpresario;
	}

	public double getAccidentesTrabajoEmpresario() {
		return this.accidentesTrabajoEmpresario;
	}

	public void setAccidentesTrabajoEmpresario(double accidentesTrabajoEmpresario) {
		this.accidentesTrabajoEmpresario = accidentesTrabajoEmpresario;
	}

	public double getImporteAccidentesTrabajoEmpresario() {
		return this.importeAccidentesTrabajoEmpresario;
	}

	public void setImporteAccidentesTrabajoEmpresario(double importeAccidentesTrabajoEmpresario) {
		this.importeAccidentesTrabajoEmpresario = importeAccidentesTrabajoEmpresario;
	}

	public double getFogasaempresario() {
		return this.fogasaempresario;
	}

	public void setFogasaempresario(double fogasaempresario) {
		this.fogasaempresario = fogasaempresario;
	}

	public double getImporteFogasaempresario() {
		return this.importeFogasaempresario;
	}

	public void setImporteFogasaempresario(double importeFogasaempresario) {
		this.importeFogasaempresario = importeFogasaempresario;
	}

	public double getSeguridadSocialTrabajador() {
		return this.seguridadSocialTrabajador;
	}

	public void setSeguridadSocialTrabajador(double seguridadSocialTrabajador) {
		this.seguridadSocialTrabajador = seguridadSocialTrabajador;
	}

	public double getImporteSeguridadSocialTrabajador() {
		return this.importeSeguridadSocialTrabajador;
	}

	public void setImporteSeguridadSocialTrabajador(double importeSeguridadSocialTrabajador) {
		this.importeSeguridadSocialTrabajador = importeSeguridadSocialTrabajador;
	}

	public double getDesempleoTrabajador() {
		return this.desempleoTrabajador;
	}

	public void setDesempleoTrabajador(double desempleoTrabajador) {
		this.desempleoTrabajador = desempleoTrabajador;
	}

	public double getImporteDesempleoTrabajador() {
		return this.importeDesempleoTrabajador;
	}

	public void setImporteDesempleoTrabajador(double importeDesempleoTrabajador) {
		this.importeDesempleoTrabajador = importeDesempleoTrabajador;
	}

	public double getFormacionTrabajador() {
		return this.formacionTrabajador;
	}

	public void setFormacionTrabajador(double formacionTrabajador) {
		this.formacionTrabajador = formacionTrabajador;
	}

	public double getImporteFormacionTrabajador() {
		return this.importeFormacionTrabajador;
	}

	public void setImporteFormacionTrabajador(double importeFormacionTrabajador) {
		this.importeFormacionTrabajador = importeFormacionTrabajador;
	}

	public double getBrutoNomina() {
		return this.brutoNomina;
	}

	public void setBrutoNomina(double brutoNomina) {
		this.brutoNomina = brutoNomina;
	}

	public double getLiquidoNomina() {
		return this.liquidoNomina;
	}

	public void setLiquidoNomina(double liquidoNomina) {
		this.liquidoNomina = liquidoNomina;
	}

	public double getCosteTotalEmpresario() {
		return this.costeTotalEmpresario;
	}

	public void setCosteTotalEmpresario(double costeTotalEmpresario) {
		this.costeTotalEmpresario = costeTotalEmpresario;
	}

}
