package models;
// Generated 30-may-2018 16:39:10 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Query;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.Session;
import org.hibernate.Transaction;

import utils.HibernateUtil;

/**
 * Trabajadorbbdd generated by hbm2java
 */
@Entity
@Table(name="Categorias")
public class Trabajadorbbdd implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
	private Integer idTrabajador;
	@Column
	private Categorias categorias;
	@Column
	private int IdEmpresa;
	@Column
	private String nombre;
	@Column
	private String apellido1;
	@Column
	private String apellido2;
	@Column
	private String nifnie;
	@Column
	private String email;
	@Column
	private Date fechaAlta;
	

	  @JoinColumn(name = "IdCategoria")
	  private int IdCategoria;

	@Column
	private String codigoCuenta;
	@Column
	private String iban;
<<<<<<< HEAD
	
	@Transient
	private int fila;
	
	@Transient
	private String  categoria;
	
	@Transient 
	private Boolean prorrateo;
	
	@Transient
	private String pais;

	public Boolean getProrrateo() {
		return prorrateo;
	}

	public void setProrrateo(Boolean prorrateo) {
		this.prorrateo = prorrateo;
	}
=======
>>>>>>> branch 'master' of https://github.com/hridog00/hibernate.git

	public Trabajadorbbdd() {
	}



/*	public Trabajadorbbdd(Categorias categorias, Empresas empresas, String nombre, String apellido1, String apellido2,
			String nifnie, String email, Date fechaAlta, String codigoCuenta, String iban, Set nominas) {
		this.categorias = categorias;
		this.empresas = empresas;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.nifnie = nifnie;
		this.email = email;
		this.fechaAlta = fechaAlta;
		this.codigoCuenta = codigoCuenta;
		this.iban = iban;
	}
*/
	public Integer getIdTrabajador() {
		return this.idTrabajador;
	}

	public void setIdTrabajador(Integer idTrabajador) {
		this.idTrabajador = idTrabajador;
	}

	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	public int getIdEmpresa() {
		return this.IdEmpresa;
	}

	public void setEmpresas(int id) {


		IdEmpresa = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getNifnie() {
		return this.nifnie;
	}

	public void setNifnie(String nifnie) {
		this.nifnie = nifnie;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getCodigoCuenta() {
		return this.codigoCuenta;
	}

	public void setCodigoCuenta(String codigoCuenta) {
		this.codigoCuenta = codigoCuenta;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

<<<<<<< HEAD
	public int getFila() {
		return fila;
	}

	public void setFila(int fila) {
		this.fila = fila;
	}

	public int getIdCategoria() {
		return IdCategoria;
	}

	public void setIdCategoria(int id) {
		
		IdCategoria = id;
		
	}

	public String getPais() {
		return pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	/*public Set getNominas() {
		return this.nominas;
	}

	public void setNominas(Set nominas) {
		this.nominas = nominas;
	}*/
	
	

=======
>>>>>>> branch 'master' of https://github.com/hridog00/hibernate.git
}
